---
- name: Build Docker images for fullstack app
  hosts: localhost
  tasks:
    - name: Build backend image
      community.docker.docker_image:
        name: misbah2/backend-demo
        tag: latest
        build:
          path: ./demo
        source: build
        
    - name: Build frontend image
      community.docker.docker_image:
        name: misbah2/frontend-app
        tag: latest
        build:
          path: ./frontend
        source: build
