apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fullstack   # مهم لو كل الـ deployments في namespace fullstack
spec:
  selector:
    app: backend
  type: NodePort         # يخلي الخدمة متاحة من خارج الكلاستر
  ports:
    - name: http
      protocol: TCP
      port: 8080         # البورت داخل الكلاستر
      targetPort: 8080   # البورت داخل الـ pod
      nodePort: 30101    # البورت الخارجي للوصول من الخارج


